### ISSUE TITLE
Analyze lastN performance of comet query

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#118]
Query for getting the lastN (=10) values for all mobile/static sensor takes >5sec in wirecloud.

Example: http://i101v180.intra.graz.at:30082/cdp/http/pep-comet:8666/STH/v1/contextEntities/type/static/id/Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor_DonBosco/attributes/pm10,location?lastN=10

**Comment by amarbajric** [comment]
**Update on this issue:**
After writing my own profiler for the `getMultiRawData()` method, the first suspicious aspect that popped up, was that the retrieval of data for each attribute grew almost with a factor of 15 after the first 3 to 4 queries have been sent asynchronously to mongodb.

Note that the retrieval of the `collectionObject` for each requested `entityId` (i.e. sensor) did not consume more time for every additional `entityId` and stayed almost the same.

Further investigations showed, that this behavior is closely linked to the [Pool Design](http://mongodb.github.io/node-mongodb-native/core/driver/reference/pool/) of mongodb itself. Based on the initial `poolSize` that is set in the `config.js` of the sth-comet, multiple asynchronous requests may perform worse than sequential requests.

**Example:**
Suppose the following request is sent to the sth-comet: `/STH/v1/contextEntities/type/static/id/Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor_DonBosco/attributes/pm10,temperature?lastN=10` and `poolSize` is set to the default value (i.e. 5).

In total, this request will query the mongodb `8+(8*2) = 24` times but in an asynchronous manner. As the `poolSize` is set to 5, the 6th, and all subsequent requests to the mongodb, will be put on hold as long as one of the 5 connections is not returned to the pool of connections. It is possible, that one of the first 5 requests finishes before the 6th asynchronous request is sent to mongodb, wich explains why maybe the profiler shows a bad performance beginning with the 7th or 8th request that is sent (rare case however).


**Possible solutions:**
- This case is a good example why sequential computing sometimes is better than concurrent or even parallel computing (i.e. implement the `getMultiRawData()` as a totally sequential method)
- Increase the `poolSize` argument in the `config.js` file of the sth-comet (although the max value for the `poolSize` argument has yet to be evaluated or tested)
  - This option has already been tested and yielded a significant performance improvement!

**Comment by amarbajric** [comment]
Additional SO Link: https://stackoverflow.com/questions/54634267/node-js-mongodb-find-sequential-faster-than-parallel-why
