### ISSUE TITLE
Check Data Interface to HDFS, since there are no recent data

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#119]
Since we changed to FIWARE Helm Chart no data was stored in HDFS!!!

**Comment by stfnltnr** [comment]
Updated FIWARE Helm Chart
- changed hdfs namenode URL to the new hadoop HA namenodes [[9591fb2]](https://github.com/fiware-austria/IPPR-GettingSmart/commit/9591fb2c7a851c777ff41d54f875462d11992ee1)
- changed hdfs format to json-column [[ca931b7](https://github.com/fiware-austria/IPPR-GettingSmart/commit/ca931b71483b0cd2aacd98495ab8989276aa804a)]

Missing Data issue was resolved via #123
