### ISSUE TITLE
Ansible Playbook for updating Kubernetes

### ISSUE THREAD

**Issue by mchoeti** [fiware-austria/SCDP#154]

**Comment by stfnltnr** [comment]
https://github.com/loete/ansible-k8s-simple-3node

**Comment by mchoeti** [comment]
Kubespray Possible upgrade guide
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/upgrades.md#graceful-upgrade

**Comment by mchoeti** [comment]
Example playbooks can be found here. I used them to upgrade the Testcluster from 
1.15.1 to 1.15.2
https://github.com/fiware-austria/IPPR-GettingSmart/tree/master/TestCluster/Ansible
