### ISSUE TITLE
Install Jupyter with Spark Integration

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#21]
Install Jupyter with Spark Integration in order to analyse the data stored in the SDPG

**Comment by amarbajric** [comment]
Update 1.07.2019:
- [x] Refactor Helm Charts for analytics components
  - Refinement of `README`
  - Assign fixed `NodePorts`
  - Helm Charts cleanup
  - Spark and Zeppelin now work together in both evaluated Spark modes (i.e. standalone and K8s)

**NOTE:** Jupyter was now dismissed in favor of Apache Zeppelin as the integration and support for both frameworks `Spark` and `Flink` are given by default.
