### ISSUE TITLE
Data concentrator for dealing with a large number of values

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#27]
Comet apparently has a strict limit on the number of values, on the other side browsers can only handle a certain maximum number of values.
We need an operator that reduces the number of entries in a list by replacing chunks of data with their average.
Idea: Config setting with maximum number of values. If the data collection exceeds this value, its reduces to about this given size
Update/Remark: Best implemented as additional feature within Comet. This would limit the data volume exchanged between Comet and Wirecloud

**Comment by amarbajric** [comment]
Edit: Fix timezone issue between backend and frontend
