### ISSUE TITLE
Provide HA with automatic failover for Hadoop Cluster

### ISSUE THREAD

**Issue by buchsbau13** [fiware-austria/SCDP#46]
The NameNode is a Single Point of Failure. In order to provide high availability a standby namenode is setup. 
Steps that have to be performed: 
- Create new docker images 
- Configure Automatic Failover with Zookeeper 
- Test HA cluster 
- Upgrade the cluster on Kubernetes 
- Migrate data

**Comment by stfnltnr** [comment]
Hadoop HA is deployed at namespace `hadoop-ha`
