### ISSUE TITLE
Optimize HDFS Access from Cygnus

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#47]
Cugnus is currently using the Hadoop Namenode's REST Service (WebHDFS), which is apparently way to slow for high loads. This should be refactored, using a "native" Hadoop interface.

**Comment by buchsbau13** [comment]
Check Fiware binary implementation 
Cygnus configuration: backend.impl=binary

**Comment by buchsbau13** [comment]
Currently the binary backend implementation cannot be used, as Cygnus is using an old version of hadoop-core: 

        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-core</artifactId>
            <version>1.2.1</version>
        </dependency>

Error message: cause:org.apache.hadoop.ipc.RemoteException: Server IPC version 9 cannot communicate with client version 4
