### ISSUE TITLE
SQL Importer für Impact Daten

### ISSUE THREAD

**Issue by buchsbau13** [fiware-austria/SCDP#69]
Importer für MongoDB und Hadoop
Impact Daten zwischen 31.10. und 05.11. 
SQL File --> siehe Telegram

**Comment by AnotherCodeArtist** [comment]
Will require a separate NodeRED flow that splits incoming data into chunks of historic data and sends these values in batches to Cygnus

**Comment by apruitg** [comment]
Additional NodeRED flow created: Buffering incoming data and sending it to Cygnus.
Python script to reformat the SQL dump and send it to the new NodeRED flow.
Current rate: 10.000 messages per minute (works stable without killing the cluster)
