### ISSUE TITLE
Research wirecloud connectors

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#72]
Research connectors for wirecloud
- Check if there are already connectors for draco/QuantumLeap. (ngsiv2)
- If not, get in touch with fiware to check

**Comment by NSpalek** [comment]
QL has a REST API that can be addressed by all components and sends responses as JSON.
The data is stored in the CrateDB (Time series DB).
It is intended to be used in combination with Grafana as a visualization tool, but it can also be combined with Wirecloud.

https://fiware-tutorials.readthedocs.io/en/latest/time-series-data/index.html#time-series-data-queries-quantumleap-api
https://app.swaggerhub.com/apis/smartsdk/ngsi-tsdb/0.2
https://github.com/Fiware/tutorials.Step-by-Step/blob/master/docs/time-series-data.md
