### ISSUE TITLE
QuantumLeap Connector Research

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#73]
- Check if QuantumLeap (will) support connectors for Hadoop/Spark
- Is it possible to connect a Hadoop cluster to QuantumLeap or a Spark integration

**Comment by NSpalek** [comment]
QL is meant to replace only the comet as a component, so there is no direct connection from QL to Hadoop / Spark.
In the future, Draco will serve as a replacement for the Cygnus and be extended by Cosmos for big data analysis (to work with Hadoop and others).
At the moment QL only supports CrateDB (others will follow).
So far, QL and Draco are still under incubation.

By using QL at the current stage of development, no components can be reduced or improved.

https://quantumleap.readthedocs.io/en/latest/
https://fiware-draco.readthedocs.io/en/latest/
https://catalogue-server.fiware.org/enablers/bigdata-analysis-cosmos
https://github.com/Fiware/catalogue/blob/master/processing/README.md#Knowage
https://www.fiware.org/developers/catalogue/
