### ISSUE TITLE
Get data efficient (e.g. batched) for Wirecloud Dashboard

### ISSUE THREAD

**Issue by NSpalek** [fiware-austria/SCDP#78]
Get data in batches directly from Comet to speed up the system. Currently sending many single requests.

**Comment by amarbajric** [comment]
Feature description for the v2.5.0 release can be found [here](https://github.com/amarbajric/fiware-sth-comet/blob/ippr-dev/doc/release-info/Comet_v2.5.0_Feature_Extensions.md)
