### ISSUE TITLE
Comet - Extend REST API

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#82]
Add new REST API to comet where we can:
- request multiple attributes from a single sensor
- request data from a sensor with selected attributes (with geo data included)

**Comment by apruitg** [comment]
Duplicate of #78

**Comment by amarbajric** [comment]
Feature description for the v2.5.0 release can be found [here](https://github.com/amarbajric/fiware-sth-comet/blob/ippr-dev/doc/release-info/Comet_v2.5.0_Feature_Extensions.md)
