### ISSUE TITLE
Update Hadoop Images

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#89]

**Comment by stfnltnr** [comment]
built new Docker Images with Hadoop 3.1.2 available at:
- https://hub.docker.com/r/stfnltnr/hadoop-yarn 
- https://hub.docker.com/r/stfnltnr/hadoop-namenode
- https://hub.docker.com/r/stfnltnr/hadoop-datanode

**Comment by AnotherCodeArtist** [comment]
Is part of #92!

**Comment by stfnltnr** [comment]
latest docker image version could be found [stfnltnr/hadoop](https://hub.docker.com/r/stfnltnr/hadoop/tags)
