### ISSUE TITLE
Create/Adapt HELM Chart mongodb cluster namespace

### ISSUE THREAD

**Issue by amarbajric** [fiware-austria/SCDP#93]

**Comment by amarbajric** [comment]
create/adapt HELM Chart for the mongodb cluster namespace

**Comment by AnotherCodeArtist** [comment]
Solution can be found [here](https://github.com/buchsbau13/IPPR-GettingSmart/tree/master/KubernetesInfrastructure/FIWARE-Helm/mongo-sharded)
