### ISSUE TITLE
Reduce logging output (mostly cygnus)

### ISSUE THREAD

**Issue by AnotherCodeArtist** [fiware-austria/SCDP#96]
Log files are growing rapidly, which swamps local file system. Logging needs to be reduced (ERROR level)

**Comment by januschm13** [comment]
Custom image (januschm/cygnus-ngsi:1.12.0) built from official source (https://github.com/telefonicaid/fiware-cygnus), with variable "CYGNUS_LOG_LEVEL" in Dockerfile set to "WARN"
